FROM node:lts-slim as build

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

ENV PORT 3001
EXPOSE $PORT

WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN npm install --silent

COPY . /usr/src/app

FROM nginx:alpine

COPY --from=build /usr/src/app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/conf.d

CMD ["nginx", "-g", "dameon off;"]