version: '3'
services:
  api:
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db

  frontend:
    environment: 
      NODE_PATH: ./src

  reverse-proxy:

  db:
    image: postgres:latest
    environment: 
      PGDATA: /var/lib/postgresql/data/db
    volumes:
    - pg-db:/var/lib/postgresql/data

volumes:
  pg-db: