version: '3'
services: 
  digital-timesheet:
    image: __CI_APPLICATION_REPOSITORY__:__VERSION__
    environment: 
      VIRTUAL_HOST: __VIRTUAL_HOST__
      VIRTUAL_PORT: __VIRTUAL_PORT__
      LETSENCRYPT_HOST: __VIRTUAL_HOST_SSL__
      PRODUCTION: true
      NODE_ENV: production