version: '3'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      SECRET_TOKEN_KEY: notasecretkey
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment: 
      NODE_ENV: development

  ingress:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80

  mongo:
    ports:
      - 27017:27017