version: '3'
services: 
  api:
    image: ${CI_APPLICATION_REPOSITORY}-api:${VERSION}
    environment:
      PRODUCTION: 'true'
      ENVIRONMENT: production
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  
  frontend:
    image: ${CI_APPLICATION_REPOSITORY}-frontend:${VERSION}
    environment:
      PRODUCTION: 'true'
      NODE_ENV: production

  reverse-proxy:
    image: ${CI_APPLICATION_REPOSITORY}-reverse-proxy:${VERSION}
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST_SSL}

  db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}