version: '3'
services:
  api:
    build:
      context: ./go-server
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: development
      JWT_SECRET_KEY: notasecretkey
      POSTGRES_USER: dts
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dts
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment: 
      REACT_APP_API_URI: /api/
    stdin_open: true

  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - 80:80

  db:
    environment:
      POSTGRES_USER: dts
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dts
  
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: pgadmin
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "8081:80"

volumes:
  pgadmin:
