#!/bin/bash

echo CI_APPLICATION_REPOSITORY=$CI_APPLICATION_REPOSITORY >> .env
echo VERSION=$CI_APPLICATION_TAG >> .env
echo VIRTUAL_HOST=$ENVIRONMENT_HOST >> .env
echo VIRTUAL_HOST_SSL=$ENVIRONMENT_HOST >> .env
echo VIRTUAL_PORT=$INTERNAL_PORT >> .env
echo SECRET_KEY=$SECRET_KEY >> .env

echo POSTGRES_USER=$POSTGRES_USER >> .env
echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
echo POSTGRES_DB=$POSTGRES_DB >> .env