#!/bin/bash

echo "Creating .env"

echo CI_APPLICATION_REPOSITORY=$CI_APPLICATION_REPOSITORY
echo VERSION=$CI_APPLICATION_TAG
echo VIRTUAL_HOST=$ENVIRONMENT_HOST
echo VIRTUAL_HOST_SSL=$ENVIRONMENT_HOS
echo VIRTUAL_PORT=$INTERNAL_PORT
echo SECRET_KEY=$SECRET_KEY

echo POSTGRES_USER=$POSTGRES_USER
echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD
echo POSTGRES_DB=$POSTGRES_DB

echo CI_APPLICATION_REPOSITORY=$CI_APPLICATION_REPOSITORY >> .env
echo VERSION=$CI_APPLICATION_TAG >> .env
echo VIRTUAL_HOST=$ENVIRONMENT_HOST >> .env
echo VIRTUAL_HOST_SSL=$ENVIRONMENT_HOST >> .env
echo VIRTUAL_PORT=$INTERNAL_PORT >> .env
echo SECRET_KEY=$SECRET_KEY >> .env

echo POSTGRES_USER=$POSTGRES_USER >> .env
echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
echo POSTGRES_DB=$POSTGRES_DB >> .env