// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthData struct {
	User             *User   `json:"user"`
	Token            *string `json:"token"`
	TwoFactorEnabled bool    `json:"twoFactorEnabled"`
}
