// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package modelgen

import (
	"git.maxtroughear.dev/max.troughear/digital-timesheet/go-server/orm/model"
)

type AuthData struct {
	User             *model.User `json:"user"`
	Token            *string     `json:"token"`
	TwoFactorEnabled bool        `json:"twoFactorEnabled"`
}
